### ISSUE TITLE
MacOS Install Notes & First Impressions

### ISSUE THREAD

**Issue by djbeadle** [AstusRush/AMaDiA#1]
**Context**
I saw your post on /r/coolgithubprojects and I thought I'd chime in a with a few notes on how I got this running on McOS

**Missing Packages**
I did not have `Anaconda` installed and wanted to try and run the code without it. After installing the contents of `requirements.txt` I had to manually install the following packages:

- `PyQtWebEngine`
- `packaging`

I did not install `antlr4` although there is a warning message letting me know it was not installed. 

The `try-except` import statement in `AMaDiA/AGeLib/__init__.py` obfuscated what packages were missing, consider adding a print statement in the `except` statement as well. 

https://github.com/AstusRush/AMaDiA/blob/c6cf0ffebaae02dd4088a27a251cff4b9a665679/AGeLib/__init__.py#L15-L18

**First Impressions**
The very first thing I ran in to was "how do I close the changelog?" I never figured that out, but I see that it disappeared the second time I ran the software.

At this point the application seems to be running, although I must admit most of it's mathematical capabilities are beyond me!

I tried out the plotter with some simple functions. I did notice some non-intuitive behavior when plotting things in the following orders:

- `x`
- `x = 23`

In this case the original plot of `x` does not recalculate or expand to fill the new space. Perhaps this is the intended functionality (to prevent unintentional recalculations of large plots) but I could not find a way to recalculate the equation to fill the new space on the graph.

This is a *very* cool project and I am going to keep it in mind for my calculating needs!

**Comment by AstusRush** [comment]
Thank you for your feedback!

> The very first thing I ran in to was "how do I close the changelog?"

All windows habe an "x" in the top right corner which closes them. This is the standard convention for Linux and Windows and making a different layout for MacOS would break too many other UI elements.

> I tried out the plotter with some simple functions.

The plot tab has two tabs on the left side: History and Config

In the Config tab you can set the minimum and maximum x values that are calculated. These values can be tweaked to plot everything that is relevant.

In the History tab are all plots. When rightclicking on a contextmenu opens that allows to calculate the plot again using the "New Plot" option. This option deletes the old plot and creates a new plot using the current settings from the Config tab.
"Load Plot" can be used to load the existing plot data in case one has used the "Clear Button" and wants to restore a plot without recalculating it.
Do you think I should relabel the buttons to make it more obvious or would a tooltip suffice?

> The try-except import statement in AMaDiA/AGeLib/__init__.py obfuscated what packages were missing, consider adding a print statement in the except statement as well.

That is a good point! I will take a look into this!

> I did not have Anaconda installed and wanted to try and run the code without it.

I only use anaconda standard packages thus an anaconda installation is the easiest way for people that don't have python installed already.

A list of (hopefully) all required packages is in `requirements.txt`.

PyQt5 used to include `PyQtWebEngine` but they have removed it in some version and I am unable to find any announcement that would clarify what exactly they did...
I will put it on the requirements list.

I thought `packaging` was a standard package... Apparently I was mistaken and it is merely a standard package of anaconda... I will add it to the list.

The antlr4 warning appears on my Linux Laptop, too, but I had no problems without it.
I should really google it and figure out what it does and which of the modules needs it...

**Comment by djbeadle** [comment]
The missing close button must be a oddity of QT on MacOS. For example there is no way to close the `About` screen either. 

<img width="446" alt="Screen Shot 2020-05-13 at 12 52 42 PM" src="https://user-images.githubusercontent.com/6235378/81841656-c419cb80-9518-11ea-8485-7048baeb5191.png">

Interestingly the buttons **do** appear on the `System Control` window and a different style of buttons appear on the `Chat Client` window.

<img width="952" alt="Screen Shot 2020-05-13 at 12 54 02 PM" src="https://user-images.githubusercontent.com/6235378/81841779-f3303d00-9518-11ea-819b-c50d18103ec0.png">

<img width="1130" alt="Screen Shot 2020-05-13 at 12 53 49 PM" src="https://user-images.githubusercontent.com/6235378/81841782-f4616a00-9518-11ea-95ff-38f07bc80644.png">

About the plotting, I didn't even notice the `From` and `To` settings on the `config` screen. I assumed because the simple plot `x=50` extended to the entire plotting space the more complex plot `y=x` should too.

<img width="668" alt="Screen Shot 2020-05-13 at 12 47 50 PM" src="https://user-images.githubusercontent.com/6235378/81841352-4c4ba100-9518-11ea-92b3-0bf1c699673d.png">

Perhaps changing "Load plot" on the history screen to "reload plot" would be slightly clearer? Or maybe it's just something users will figure out.

**Comment by AstusRush** [comment]
Ok... I know what happened... MacOS is hijacking the menu bar to manage it itself which overwrites my widget which includes the controls... I feared this would happen but I have no access to a Mac and thus could not verify it...
I already have a plan that would fix this but it might take a while since it requires a lot of rewriting...
I will reenable the standard MacOS window frame in the next update to make it possible to close the windows...
The System Control window has the controls in the tabWidget which makes it immune to this bug.
The Chat windows do not use my own window class and have the standard window frame enabled. (I will rework the chat in the coming months)

Automatically recalculating all plots whenever "the space gets bigger" would be extremely unpleasant if a more complicated plot like `integrate(sqrt(sin(x))/(sqrt(sin(x))+sqrt(cos(x))))` is among the displayed plots as it could take several minutes on weaker systems. I agree that it would be awesome but it is not something that can be done without slowing down the plotting.

> Perhaps changing "Load plot" on the history screen to "reload plot" would be slightly clearer?

This is a great idea! The reason I wrote "Load Plot" was because it is easy to understand if you are not in the plot tab but since it is primarily used in the plot tab the name is a poor choice.
It will be renamed in the next patch.

**Comment by AstusRush** [comment]
By the way: Pressing alt+c in the main window should bring the window controls back because this moves them to the tab widget.

But how did you even open all the other windows without the menu bar?
I can think of 4 ways (alt+c being one of them) but which one did you use?

**Comment by djbeadle** [comment]
Ahh, yes, you're quite right. I didn't find that menu option!

<img width="916" alt="Screen Shot 2020-05-13 at 5 44 45 PM" src="https://user-images.githubusercontent.com/6235378/81869157-8aa98600-9541-11ea-8f0a-6535490d018b.png">

**Comment by AstusRush** [comment]
Now I get what is meant by MacOS grabbing the menu bar!
Also: There should be an action called "Options" (shortcut alt+o) at the top of the options menu that opens the options window...

By the way: Is there a folder named "AGeLib" in your user folder? (I use that folder to store config files, custom colour palettes and screenshots (hotkey F12).) It works on Windows and Linux but I am not able to test it on MacOS.

**Comment by djbeadle** [comment]
Yep!

<img width="325" alt="Screen Shot 2020-05-13 at 5 58 24 PM" src="https://user-images.githubusercontent.com/6235378/81870225-6e0e4d80-9543-11ea-9fbb-bfb93a82303a.png">

**Comment by AstusRush** [comment]
Ok I think I found the option to keep my menubar:
```python
self.setAttribute(QtCore.Qt.AA_DontUseNativeMenuBar)
```
Could you add this in AGeLib/AGeMain.py line 530 in the init of Main_App a verify that the controls appear?
It means that Mac users don't get their menu bar where they would expect it but this is the only way for me to fix this without access to a Mac.

**Comment by djbeadle** [comment]
Looks pretty good to me! I think ensuring the presence of the minimize-maximize-close buttons is more important than having the menus in the menu bar. 

<img width="686" alt="Screen Shot 2020-05-14 at 11 33 49 AM" src="https://user-images.githubusercontent.com/6235378/81954392-ca6e7d00-95d6-11ea-9f79-2131ee832b7c.png">

**Comment by tclarke** [comment]
It's generally considered poor design to override main menus and window manager decorations. This causes cross platform issues (such as on Mac) but it also prevents the app from styling according to the user's setup. I'd suggest sticking with the default styling and if you want the option of the dark window, etc. use QStyleSheet and let the user select a "theme" then apply the css. Not only will this ensure the app looks correct for different user setups, more importantly it allows it to work appropriately for users with special display needs such as large fonts, color blindness palettes, etc.

**Comment by AstusRush** [comment]
@tclarke My library AGeLib handles the colours, font and fontsize of the gui and allows every user to fully customise the visual appearance. My options even window allows to create and save colourpallets that can then be loaded from all applications using AGeLib. The options window also allows to change the font to any installed font. Furthermore every single window has a spin box to change the font size.

I am not a fan of QStyleSheet since it disables ALL functions that change the design of the gui.

I understand why it can be considered a bad idea to overwrite system specific things like the window manager and the menu bar but I want to allow the user to fully customise the appearance of the window including the window frame and I also like to use the massive space the frame takes up.
Furthermore most modern applications overwrite the system window manager like spotify and steam and to a lesser degree google chrome, firefox, discord and VSCode to just name the ones that are currently open on my PC. There are barely any programs that don't alter the window frame (the adobe pdf viewer is the only one I have currently open...).

But I none the less appreciate your feedback.

**Comment by AstusRush** [comment]
Was a busy year so the next update takes longer than expected. I pushed a hotfix to finally fix the window frames on mac.
